// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemMagazynu.Data;

#nullable disable

namespace SystemMagazynu.Migrations
{
    [DbContext(typeof(MagazynDbContext))]
    partial class MagazynDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RezerwacjaMaterialu", b =>
                {
                    b.Property<int>("IdRezerwacji")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRezerwacji"));

                    b.Property<DateTime>("DataRezerwacji")
                        .HasColumnType("datetime2");

                    b.Property<int>("DokumentId")
                        .HasColumnType("int");

                    b.Property<int>("MagazynId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ZarezerwowanaIlosc")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdRezerwacji");

                    b.HasIndex("DokumentId");

                    b.HasIndex("MagazynId");

                    b.HasIndex("MaterialId");

                    b.ToTable("RezerwacjeMaterialow");
                });

            modelBuilder.Entity("SystemMagazynu.Models.Dokument", b =>
                {
                    b.Property<int>("IdDokumentu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDokumentu"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DostawcaId")
                        .HasColumnType("int");

                    b.Property<int>("MagazynId")
                        .HasColumnType("int");

                    b.Property<string>("NumerDokumentu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OdbiorcaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("int");

                    b.HasKey("IdDokumentu");

                    b.HasIndex("DostawcaId");

                    b.HasIndex("MagazynId");

                    b.HasIndex("OdbiorcaId");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("Dokumenty", (string)null);
                });

            modelBuilder.Entity("SystemMagazynu.Models.Dostawca", b =>
                {
                    b.Property<int>("IdDostawcy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDostawcy"));

                    b.Property<bool>("CzyAktywny")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDostawcy");

                    b.ToTable("Dostawcy");
                });

            modelBuilder.Entity("SystemMagazynu.Models.LogBledu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Akcja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Komunikat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kontroler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogiBledow");
                });

            modelBuilder.Entity("SystemMagazynu.Models.Magazyn", b =>
                {
                    b.Property<int>("IdMagazynu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMagazynu"));

                    b.Property<string>("Lokalizacja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMagazynu");

                    b.ToTable("Magazyny");
                });

            modelBuilder.Entity("SystemMagazynu.Models.Material", b =>
                {
                    b.Property<int>("IdMaterialu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMaterialu"));

                    b.Property<string>("Jednostka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMaterialu");

                    b.ToTable("Materialy");
                });

            modelBuilder.Entity("SystemMagazynu.Models.Odbiorca", b =>
                {
                    b.Property<int>("IdOdbiorcy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOdbiorcy"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CzyAktywny")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdOdbiorcy");

                    b.ToTable("Odbiorcy");
                });

            modelBuilder.Entity("SystemMagazynu.Models.PozycjaDokumentu", b =>
                {
                    b.Property<int>("IdPozycji")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPozycji"));

                    b.Property<int>("DokumentId")
                        .HasColumnType("int");

                    b.Property<decimal>("Ilosc")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.HasKey("IdPozycji");

                    b.HasIndex("DokumentId");

                    b.HasIndex("MaterialId");

                    b.ToTable("PozycjeDokumentow", (string)null);
                });

            modelBuilder.Entity("SystemMagazynu.Models.StanMagazynowy", b =>
                {
                    b.Property<int>("MagazynId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<decimal>("Ilosc")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("MagazynId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("StanyMagazynowe");
                });

            modelBuilder.Entity("SystemMagazynu.Models.Uzytkownik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CzyAktywny")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataRejestracji")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HasloHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rola")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Uzytkownicy");
                });

            modelBuilder.Entity("RezerwacjaMaterialu", b =>
                {
                    b.HasOne("SystemMagazynu.Models.Dokument", "Dokument")
                        .WithMany()
                        .HasForeignKey("DokumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemMagazynu.Models.Magazyn", "Magazyn")
                        .WithMany()
                        .HasForeignKey("MagazynId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemMagazynu.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dokument");

                    b.Navigation("Magazyn");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("SystemMagazynu.Models.Dokument", b =>
                {
                    b.HasOne("SystemMagazynu.Models.Dostawca", "Dostawca")
                        .WithMany("Dokumenty")
                        .HasForeignKey("DostawcaId");

                    b.HasOne("SystemMagazynu.Models.Magazyn", "Magazyn")
                        .WithMany("Dokumenty")
                        .HasForeignKey("MagazynId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemMagazynu.Models.Odbiorca", "Odbiorca")
                        .WithMany("Dokumenty")
                        .HasForeignKey("OdbiorcaId");

                    b.HasOne("SystemMagazynu.Models.Uzytkownik", "Uzytkownik")
                        .WithMany("Dokumenty")
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dostawca");

                    b.Navigation("Magazyn");

                    b.Navigation("Odbiorca");

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("SystemMagazynu.Models.PozycjaDokumentu", b =>
                {
                    b.HasOne("SystemMagazynu.Models.Dokument", "Dokument")
                        .WithMany("Pozycje")
                        .HasForeignKey("DokumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemMagazynu.Models.Material", "Material")
                        .WithMany("PozycjeDokumentow")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dokument");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("SystemMagazynu.Models.StanMagazynowy", b =>
                {
                    b.HasOne("SystemMagazynu.Models.Magazyn", "Magazyn")
                        .WithMany("StanyMagazynowe")
                        .HasForeignKey("MagazynId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemMagazynu.Models.Material", "Material")
                        .WithMany("StanyMagazynowe")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Magazyn");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("SystemMagazynu.Models.Dokument", b =>
                {
                    b.Navigation("Pozycje");
                });

            modelBuilder.Entity("SystemMagazynu.Models.Dostawca", b =>
                {
                    b.Navigation("Dokumenty");
                });

            modelBuilder.Entity("SystemMagazynu.Models.Magazyn", b =>
                {
                    b.Navigation("Dokumenty");

                    b.Navigation("StanyMagazynowe");
                });

            modelBuilder.Entity("SystemMagazynu.Models.Material", b =>
                {
                    b.Navigation("PozycjeDokumentow");

                    b.Navigation("StanyMagazynowe");
                });

            modelBuilder.Entity("SystemMagazynu.Models.Odbiorca", b =>
                {
                    b.Navigation("Dokumenty");
                });

            modelBuilder.Entity("SystemMagazynu.Models.Uzytkownik", b =>
                {
                    b.Navigation("Dokumenty");
                });
#pragma warning restore 612, 618
        }
    }
}
